// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGMTdF1qhL0zC1s5brPUofTf2SOFNLClk',
    appId: '1:281921997914:web:0acff13b863e1597861c63',
    messagingSenderId: '281921997914',
    projectId: 'waterloo-masjid-app-a1dd9',
    authDomain: 'waterloo-masjid-app-a1dd9.firebaseapp.com',
    storageBucket: 'waterloo-masjid-app-a1dd9.appspot.com',
    measurementId: 'G-HVRH019FHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-MsyzVEB0rxoJ1U3WfXa9NkMF6npLxVw',
    appId: '1:281921997914:android:50121318ee037333861c63',
    messagingSenderId: '281921997914',
    projectId: 'waterloo-masjid-app-a1dd9',
    storageBucket: 'waterloo-masjid-app-a1dd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGwV2FqKPivmF8YOy7o0gKX0OGXAYiBH0',
    appId: '1:281921997914:ios:0f9c94f928eeb198861c63',
    messagingSenderId: '281921997914',
    projectId: 'waterloo-masjid-app-a1dd9',
    storageBucket: 'waterloo-masjid-app-a1dd9.appspot.com',
    iosClientId: '281921997914-vresitbs1s2hv026iak0hi3istnlo2d1.apps.googleusercontent.com',
    iosBundleId: 'com.waterloomasjid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGwV2FqKPivmF8YOy7o0gKX0OGXAYiBH0',
    appId: '1:281921997914:ios:0f9c94f928eeb198861c63',
    messagingSenderId: '281921997914',
    projectId: 'waterloo-masjid-app-a1dd9',
    storageBucket: 'waterloo-masjid-app-a1dd9.appspot.com',
    iosClientId: '281921997914-vresitbs1s2hv026iak0hi3istnlo2d1.apps.googleusercontent.com',
    iosBundleId: 'com.waterloomasjid',
  );
}
